project_id = "lfbsayozyvhmxsuzatpj"

[functions.ai-search]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.admin-check]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.admin-seed]
verify_jwt = false
